/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#403f3f",
        "primary-fixed": "#e5e2e1",
        "secondary-container": "#f3dfcf",
        "on-tertiary-fixed-variant": "#626265",
        "inverse-on-surface": "#9f9c99",
        "outline-variant": "#bcb9b1",
        "error": "#a54731",
        "secondary": "#716255",
        "on-secondary-fixed": "#4a3d32",
        "secondary-dim": "#64564a",
        "surface-container-high": "#f1ede6",
        "surface-tint": "#5f5e5e",
        "surface-container-highest": "#ebe8e0",
        "surface-container-low": "#fdf9f4",
        "surface-container": "#f7f3ed",
        "on-secondary-fixed-variant": "#67594d",
        "primary-dim": "#535252",
        "tertiary-fixed": "#eeedf0",
        "on-surface": "#393832",
        "on-background": "#393832",
        "on-secondary-container": "#5d4f43",
        "surface-bright": "#fffbff",
        "on-primary": "#faf7f6",
        "inverse-surface": "#0f0e0c",
        "on-tertiary-container": "#57585a",
        "surface-dim": "#e6e2d9",
        "surface": "#fffbff",
        "primary-fixed-dim": "#d6d4d3",
        "surface-variant": "#ebe8e0",
        "on-tertiary": "#ffffff",
        "background": "#fffbff",
        "inverse-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "outline": "#82807a",
        "secondary-fixed": "#f3dfcf",
        "tertiary": "#646466",
        "error-dim": "#5c1202",
        "primary": "#5f5e5e",
        "on-tertiary-fixed": "#454648",
        "tertiary-fixed-dim": "#e0dfe1",
        "on-error": "#ffffff",
        "error-container": "#fe8b70",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#742410",
        "on-primary-container": "#525151",
        "on-surface-variant": "#66645e",
        "on-primary-fixed-variant": "#5c5b5b",
        "secondary-fixed-dim": "#e5d1c2",
        "tertiary-container": "#eeedf0",
        "tertiary-dim": "#57585a",
        "primary-container": "#e5e2e1"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
